/*
	SwiftyStrings.swift
	Speech

	Generated by SwiftyAssets 🦊 on 17/05/2021
	Copyright © 2021, Speech. All rights reserved.
*/

import Foundation

extension SwiftyAssets {
	class Strings {
		static var settings_made_in_auvergne: String {
			return NSLocalizedString("settings_made_in_auvergne", comment: "")
		}

		static var generic_clear: String {
			return NSLocalizedString("generic_clear", comment: "")
		}

		static var settings_preferences: String {
			return NSLocalizedString("settings_preferences", comment: "")
		}

		static var editor_area_duplication_title: String {
			return NSLocalizedString("editor_area_duplication_title", comment: "")
		}

		static var generic_add: String {
			return NSLocalizedString("generic_add", comment: "")
		}

		static var messages_list_empty_search_body: String {
			return NSLocalizedString("messages_list_empty_search_body", comment: "")
		}

		static var new_category_title: String {
			return NSLocalizedString("new_category_title", comment: "")
		}

		static var welcome_title: String {
			return NSLocalizedString("welcome_title", comment: "")
		}

		static var preferences_speaking_rate: String {
			return NSLocalizedString("preferences_speaking_rate", comment: "")
		}

		static var settings_privacy_policy: String {
			return NSLocalizedString("settings_privacy_policy", comment: "")
		}

		static var welcome_slogan: String {
			return NSLocalizedString("welcome_slogan", comment: "")
		}

		static var message_emoji_and_message: String {
			return NSLocalizedString("message_emoji_and_message", comment: "")
		}

		static var editor_area_placeholder: String {
			return NSLocalizedString("editor_area_placeholder", comment: "")
		}

		static var generic_messages: String {
			return NSLocalizedString("generic_messages", comment: "")
		}

		static var message_new_title: String {
			return NSLocalizedString("message_new_title", comment: "")
		}

		static var messages_list_sort_by_alphabetical_order: String {
			return NSLocalizedString("messages_list_sort_by_alphabetical_order", comment: "")
		}

		static var editor_area_empty_text_on_save_title: String {
			return NSLocalizedString("editor_area_empty_text_on_save_title", comment: "")
		}

		static var generic_edit: String {
			return NSLocalizedString("generic_edit", comment: "")
		}

		static var generic_validate: String {
			return NSLocalizedString("generic_validate", comment: "")
		}

		static var generic_cancel: String {
			return NSLocalizedString("generic_cancel", comment: "")
		}

		static var message_edit_title: String {
			return NSLocalizedString("message_edit_title", comment: "")
		}

		static var welcome_description: String {
			return NSLocalizedString("welcome_description", comment: "")
		}

		static var messages_list_empty_body: String {
			return NSLocalizedString("messages_list_empty_body", comment: "")
		}

		static var editor_area_successfully_saved_body: String {
			return NSLocalizedString("editor_area_successfully_saved_body", comment: "")
		}

		static var preferences_show_frequently_used_messages: String {
			return NSLocalizedString("preferences_show_frequently_used_messages", comment: "")
		}

		static var messages_list_empty_search_title: String {
			return NSLocalizedString("messages_list_empty_search_title", comment: "")
		}

		static var editor_area_empty_text_on_save_body: String {
			return NSLocalizedString("editor_area_empty_text_on_save_body", comment: "")
		}

		static var preferences_save_messages_quickly: String {
			return NSLocalizedString("preferences_save_messages_quickly", comment: "")
		}

		static var settings_open_source: String {
			return NSLocalizedString("settings_open_source", comment: "")
		}

		static var generic_delete: String {
			return NSLocalizedString("generic_delete", comment: "")
		}

		static var editor_area_successfully_saved_title: String {
			return NSLocalizedString("editor_area_successfully_saved_title", comment: "")
		}

		static var messages_list_empty_title: String {
			return NSLocalizedString("messages_list_empty_title", comment: "")
		}

		static var editor_area_duplication_body: String {
			return NSLocalizedString("editor_area_duplication_body", comment: "")
		}

		static var settings_share_app: String {
			return NSLocalizedString("settings_share_app", comment: "")
		}

		static var generic_settings: String {
			return NSLocalizedString("generic_settings", comment: "")
		}

		static var settings_rate_app: String {
			return NSLocalizedString("settings_rate_app", comment: "")
		}

		static var settings_github: String {
			return NSLocalizedString("settings_github", comment: "")
		}

		static var messages_all: String {
			return NSLocalizedString("messages_all", comment: "")
		}

		static var settings_about: String {
			return NSLocalizedString("settings_about", comment: "")
		}

		static var preferences_voice: String {
			return NSLocalizedString("preferences_voice", comment: "")
		}

		static var welcome_get_started: String {
			return NSLocalizedString("welcome_get_started", comment: "")
		}

		static var messages_frequently_used: String {
			return NSLocalizedString("messages_frequently_used", comment: "")
		}

		static var editor_area_not_successfully_saved_body: String {
			return NSLocalizedString("editor_area_not_successfully_saved_body", comment: "")
		}

		static var messages_list_sort_by_date_added: String {
			return NSLocalizedString("messages_list_sort_by_date_added", comment: "")
		}

		static var generic_category: String {
			return NSLocalizedString("generic_category", comment: "")
		}

		static var editor_area_not_successfully_saved_title: String {
			return NSLocalizedString("editor_area_not_successfully_saved_title", comment: "")
		}

		static var preferences_editor_area_text_size: String {
			return NSLocalizedString("preferences_editor_area_text_size", comment: "")
		}

		static var about_description: String {
			return NSLocalizedString("about_description", comment: "")
		}

		static var settings_thanks: String {
			return NSLocalizedString("settings_thanks", comment: "")
		}

		static var generic_create: String {
			return NSLocalizedString("generic_create", comment: "")
		}

		static var generic_categories: String {
			return NSLocalizedString("generic_categories", comment: "")
		}

		static var generic_save: String {
			return NSLocalizedString("generic_save", comment: "")
		}

		static var settings_speech_synthesis: String {
			return NSLocalizedString("settings_speech_synthesis", comment: "")
		}

	}
}
