/*
    SwiftyImages.swift
    Speech

    Generated by SwiftyAssets 🦊 on 21/04/2021
    Copyright © 2020, Speech. All rights reserved.
*/

#if canImport(UIKit)
import UIKit

// swiftlint:disable force_unwrapping
extension SwiftyAssets {
    class Images {
        static var no_messages: UIImage {
            return UIImage(named: "no_messages")!
        }
        
        static var ellipsis_circle: UIImage {
            return UIImage(named: "ellipsis_circle")!
        }
        
        static var play_circle: UIImage {
            return UIImage(named: "play_circle")!
        }
        
        static var gearshape: UIImage {
            return UIImage(named: "gearshape")!
        }
        
        static var stop_circle: UIImage {
            return UIImage(named: "stop_circle")!
        }
        
        static var smileys_and_people: UIImage {
            return UIImage(named: "smileys_and_people")!
        }
        
        static var pause_circle: UIImage {
            return UIImage(named: "pause_circle")!
        }
        
        static var app_icon: UIImage {
            return UIImage(named: "app_icon")!
        }
        
        static var line_horizontal_3_circle: UIImage {
            return UIImage(named: "line_horizontal_3_circle")!
        }
        
        static var welcome: UIImage {
            return UIImage(named: "welcome")!
        }
    }
}
// swiftlint:enable force_unwrapping
#endif
