/*
	SwiftyImages.swift
	Speech

	Generated by SwiftyAssets 🦊 on 06/04/2021
	Copyright © 2020, Speech. All rights reserved.
*/

import UIKit

// swiftlint:disable force_unwrapping
extension SwiftyAssets {
	class Images {
		static var pause_circle: UIImage {
			return UIImage(named: "pause_circle")!
		}

		static var play_circle: UIImage {
			return UIImage(named: "play_circle")!
		}

		static var line_horizontal_3_circle: UIImage {
			return UIImage(named: "line_horizontal_3_circle")!
		}

		static var stop_circle: UIImage {
			return UIImage(named: "stop_circle")!
		}

		static var ellipsis_circle: UIImage {
			return UIImage(named: "ellipsis_circle")!
		}

		static var no_messages: UIImage {
			return UIImage(named: "no_messages")!
		}

		static var gearshape: UIImage {
			return UIImage(named: "gearshape")!
		}

		static var app_icon: UIImage {
			return UIImage(named: "app_icon")!
		}

	}
}
// swiftlint:enable force_unwrapping
