/*
    SwiftyColors.swift
    Speech

    Generated by SwiftyAssets 🦊 on 07/04/2021
    Copyright © 2020, Speech. All rights reserved.
*/

#if canImport(UIKit)
import UIKit

// swiftlint:disable force_unwrapping
extension SwiftyAssets {
    class UIColors {
        static var primary: UIColor {
            return UIColor(named: "primary")!
        }
    }
}
// swiftlint:enable force_unwrapping
#endif

#if canImport(SwiftUI)
import SwiftUI

@available(iOS 13.0, *)
extension SwiftyAssets {
    class Colors {
        static var primary: Color {
            return Color("primary")
        }
    }
}
#endif
