/*
	SwiftyStrings.swift
	Speech

	Generated by SwiftyAssets 🦊 on 06/04/2021
	Copyright © 2020, Speech. All rights reserved.
*/

import Foundation

extension SwiftyAssets {
	class Strings {
		static var settings_thanks: String {
			return NSLocalizedString("settings_thanks", comment: "")
		}

		static var editor_area_successfully_saved_title: String {
			return NSLocalizedString("editor_area_successfully_saved_title", comment: "")
		}

		static var generic_settings: String {
			return NSLocalizedString("generic_settings", comment: "")
		}

		static var generic_version: String {
			return NSLocalizedString("generic_version", comment: "")
		}

		static var generic_delete: String {
			return NSLocalizedString("generic_delete", comment: "")
		}

		static var messages_list_sort_by_date_added: String {
			return NSLocalizedString("messages_list_sort_by_date_added", comment: "")
		}

		static var settings_made_in_auvergne: String {
			return NSLocalizedString("settings_made_in_auvergne", comment: "")
		}

		static var generic_save: String {
			return NSLocalizedString("generic_save", comment: "")
		}

		static var generic_validate: String {
			return NSLocalizedString("generic_validate", comment: "")
		}

		static var editor_area_duplication_body: String {
			return NSLocalizedString("editor_area_duplication_body", comment: "")
		}

		static var generic_edit: String {
			return NSLocalizedString("generic_edit", comment: "")
		}

		static var editor_area_duplication_title: String {
			return NSLocalizedString("editor_area_duplication_title", comment: "")
		}

		static var generic_messages: String {
			return NSLocalizedString("generic_messages", comment: "")
		}

		static var editor_area_successfully_saved_body: String {
			return NSLocalizedString("editor_area_successfully_saved_body", comment: "")
		}

		static var message_new_title: String {
			return NSLocalizedString("message_new_title", comment: "")
		}

		static var settings_open_source: String {
			return NSLocalizedString("settings_open_source", comment: "")
		}

		static var editor_area_not_successfully_saved_title: String {
			return NSLocalizedString("editor_area_not_successfully_saved_title", comment: "")
		}

		static var settings_voice: String {
			return NSLocalizedString("settings_voice", comment: "")
		}

		static var editor_area_empty_text_on_save_body: String {
			return NSLocalizedString("editor_area_empty_text_on_save_body", comment: "")
		}

		static var editor_area_not_successfully_saved_body: String {
			return NSLocalizedString("editor_area_not_successfully_saved_body", comment: "")
		}

		static var generic_cancel: String {
			return NSLocalizedString("generic_cancel", comment: "")
		}

		static var settings_about: String {
			return NSLocalizedString("settings_about", comment: "")
		}

		static var editor_area_placeholder: String {
			return NSLocalizedString("editor_area_placeholder", comment: "")
		}

		static var editor_area_empty_text_on_save_title: String {
			return NSLocalizedString("editor_area_empty_text_on_save_title", comment: "")
		}

		static var settings_appearance: String {
			return NSLocalizedString("settings_appearance", comment: "")
		}

		static var messages_list_empty: String {
			return NSLocalizedString("messages_list_empty", comment: "")
		}

		static var generic_clear: String {
			return NSLocalizedString("generic_clear", comment: "")
		}

		static var messages_list_sort_by_alphabetical_order: String {
			return NSLocalizedString("messages_list_sort_by_alphabetical_order", comment: "")
		}

	}
}
