/*
    SwiftyColors.swift
    Speech

    Generated by SwiftyAssets 🦊 on 23/09/2021
    Copyright © 2021, Speech. All rights reserved.
*/

#if canImport(UIKit)
import UIKit

// swiftlint:disable force_unwrapping
extension SwiftyAssets {
    class UIColors {
        static var warning: UIColor {
            return UIColor(named: "warning")!
        }
        
        static var secondary_fill: UIColor {
            return UIColor(named: "secondary_fill")!
        }
        
        static var error: UIColor {
            return UIColor(named: "error")!
        }
        
        static var primary: UIColor {
            return UIColor(named: "primary")!
        }
    }
}
// swiftlint:enable force_unwrapping
#endif

#if canImport(SwiftUI)
import SwiftUI

@available(iOS 13.0, *)
extension SwiftyAssets {
    class Colors {
        static var warning: Color {
            return Color("warning")
        }
        
        static var secondary_fill: Color {
            return Color("secondary_fill")
        }
        
        static var error: Color {
            return Color("error")
        }
        
        static var primary: Color {
            return Color("primary")
        }
    }
}
#endif
