/*
    SwiftyImages.swift
    Speech

    Generated by SwiftyAssets 🦊 on 11/05/2021
    Copyright © 2020, Speech. All rights reserved.
*/

#if canImport(UIKit)
import UIKit

// swiftlint:disable force_unwrapping
extension SwiftyAssets {
    class UIImages {
        static var gearshape: UIImage {
            return UIImage(named: "gearshape")!
        }
        
        static var smileys_and_people: UIImage {
            return UIImage(named: "smileys_and_people")!
        }
        
        static var ellipsis_circle: UIImage {
            return UIImage(named: "ellipsis_circle")!
        }
        
        static var app_icon: UIImage {
            return UIImage(named: "app_icon")!
        }
        
        static var welcome: UIImage {
            return UIImage(named: "welcome")!
        }
        
        static var line_horizontal_3_circle: UIImage {
            return UIImage(named: "line_horizontal_3_circle")!
        }
        
        static var pause_circle: UIImage {
            return UIImage(named: "pause_circle")!
        }
        
        static var stop_circle: UIImage {
            return UIImage(named: "stop_circle")!
        }
        
        static var play_circle: UIImage {
            return UIImage(named: "play_circle")!
        }
        
        static var tortoise: UIImage {
            return UIImage(named: "tortoise")!
        }
        
        static var hare: UIImage {
            return UIImage(named: "hare")!
        }
        
        static var no_messages: UIImage {
            return UIImage(named: "no_messages")!
        }
    }
}
// swiftlint:enable force_unwrapping
#endif

#if canImport(SwiftUI)
import SwiftUI

@available(iOS 13.0, *)
extension SwiftyAssets {
    class Images {
        static var gearshape: Image {
            return Image("gearshape")
        }
        
        static var smileys_and_people: Image {
            return Image("smileys_and_people")
        }
        
        static var ellipsis_circle: Image {
            return Image("ellipsis_circle")
        }
        
        static var app_icon: Image {
            return Image("app_icon")
        }
        
        static var welcome: Image {
            return Image("welcome")
        }
        
        static var line_horizontal_3_circle: Image {
            return Image("line_horizontal_3_circle")
        }
        
        static var pause_circle: Image {
            return Image("pause_circle")
        }
        
        static var stop_circle: Image {
            return Image("stop_circle")
        }
        
        static var play_circle: Image {
            return Image("play_circle")
        }
        
        static var tortoise: Image {
            return Image("tortoise")
        }
        
        static var hare: Image {
            return Image("hare")
        }
        
        static var no_messages: Image {
            return Image("no_messages")
        }
    }
}
#endif
