name: Build & Test

on:
  push:
    branches:
      - '**'
    paths:
      - '**.swift'
      - '**/build_test.yml'
      - '.github.env'
  workflow_dispatch:

env:
  DERIVED_DATA_PATH: "./DerivedData"
  BUILD_PRODUCTS_ARTIFACT_NAME: "build_products"

jobs:  
  lint:
    name: Lint
    runs-on: macos-11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Swiftlint
        run: swiftlint lint --reporter github-actions-logging
  
  build:
    name: Build
    runs-on: macos-11
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive
      - name: Set env from .github.env file
        uses: JeanCharlesNeboit/action-dotenv-to-setenv@main
        with:
          env-file: .github.env
      - name: Decrypt gpg files
        run: ./SwiftyCI/scripts/decrypt_secret.sh ${{ env.GPG_FILES }}
        env:
          PASSPHRASE: ${{ secrets.GPG_SECRET }}
      - name: Xcode select
        if: ${{ env.XCODE != '' }}
        uses: ./SwiftyCI/actions/xcode_select
        with:
          xcode: ${{ env.XCODE }}
      - name: Run build action
        id: build
        uses: ./SwiftyCI/actions/build
        with:
          scheme: ${{ env.SCHEME }}
          derivedDataPath: ${{ env.DERIVED_DATA_PATH }}
      - if: ${{ steps.build.outputs.exit_code != 0 }}
        name: Upload xcodebuild log
        uses: actions/upload-artifact@v2
        with:
          name: xcodebuild.log
          path: ./xcodebuild.log
      - if: ${{ steps.build.outputs.exit_code == 0 }}
        name: Upload build products
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUILD_PRODUCTS_ARTIFACT_NAME }}
          path: ${{ env.DERIVED_DATA_PATH }}/Build/Products
  
  test:
    name: Test
    runs-on: macos-11
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive
      - name: Set env from .github.env file
        uses: JeanCharlesNeboit/action-dotenv-to-setenv@main
        with:
          env-file: .github.env
      - name: Xcode select
        if: ${{ env.XCODE != '' }}
        uses: ./SwiftyCI/actions/xcode_select
        with:
          xcode: ${{ env.XCODE }}
      - name: Download products
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.BUILD_PRODUCTS_ARTIFACT_NAME }}
      - name: Run test action
        uses: ./SwiftyCI/actions/test